name: Notify on Branch Creation

on:
  push:
    branches:
      - '*' # Trigger on push to any branch.
  create:
    ref_type: branch
  

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify on Microsoft Teams
        uses: m365/actions-teams-message@v1
        with:
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          message: |
            ## New Branch Created
            A new branch **${{ github.ref_name }}** was created in the repository **${{ github.repository }}**.
