name: Notify on Branch Creation

on:
  push:
    branches:
      - '*' # Trigger on push to any branch.
  create:
    ref_type: branch
  

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        run: |
          curl -X POST \
            --url https://api.sendgrid.com/v3/mail/send \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "personalizations": [{
                "to": [{"email": "nicole-anne.paterson-jones@ext.ec.europa.eu"}],
                "subject": "New Branch Created: ${{ github.ref_name }}"
              }],
              "from": {"email": "noreply@OP-TEDDocs.com"},
              "content": [{"type": "text/plain", "value": "A new branch was created in the repository ${{ github.repository }}."}]
            }'
